#!/usr/bin/env bash
[[ -n $DEBUG ]] && set -x
set -eou pipefail

usage() {
    cat <<HELP
USAGE:
    install-local-provider REPO NAME
HELP
}

exit_err() {
    echo >&2 "${1}"
    exit 1
}

if [ $# -lt 2 ]; then
    usage
    exit 1
fi

REPO=$1
NAME=$2
VERSION=${3:-"0.0.0-master"}

PROVIDERS_DIR=$HOME/.terraform.d/plugins/registry.terraform.io/${REPO}/${NAME}
PROVIDER_DIR=${PROVIDERS_DIR}/${VERSION}/linux_amd64
mkdir -p ${PROVIDER_DIR}
cp ./terraform-provider-${NAME} ${PROVIDER_DIR}/terraform-provider-${NAME}_v${VERSION}
