scan_timeout = 10
[directory]
truncate_to_repo = false
[golang]
symbol = "go-"
[nodejs]
symbol = "node-"
[python]
symbol = "python-"
[rust]
symbol = "rust-"
[java]
symbol = "jdk-"
[kubernetes]
symbol = "⛵ "
style = "dim green"
disabled = true
[git_branch]
disabled = false
[git_commit]
disabled = true
[git_state]
disabled = true
[git_status]
disabled = true
