[directory]
truncate_to_repo = false
[golang]
symbol = "go-"
[nodejs]
symbol = "node-"
[python]
symbol = "python-"
[rust]
symbol = "rust-"
[java]
symbol = "jdk-"
[kubernetes]
symbol = "⛵ "
style = "dim green"
disabled = true
